pipeline {
    agent any
    stages {
        stage('flyway') {
            environment {
               flywayHome = tool 'flyway'
            }
            steps {
                sh 'ls ${env.WORKSPACE}'
                sh '${flywayHome}/flyway -url=jdbc:postgresql://pg:5432/scm -user=scm -password=scm info'
            }
        }
    }
}