pipeline {
    agent any
    stages {
        stage('flyway') {
            environment {
               flywayHome = tool 'flyway'
            }
            steps {
                sh 'ls ${flywayHome}'
                sh '${flywayHome}/flyway -configFiles=${env.WORKSPACE}/conf/flyway.conf -url=jdbc:postgresql://pg:5432/scm -user=scm -password=scm info'
            }
        }
    }
}