CREATE TABLE scm.w_item(
 lot_number varchar(22) NOT NULL,
 eai_update_date varchar(18) NOT NULL,
 eai_update_type varchar(1) NOT NULL,
 eai_send_status varchar(1),
 eai_send_date varchar(18),
 batch_region numeric(2) NOT NULL,
 system_business_code varchar(10) NOT NULL,
 item_code varchar(25) NOT NULL,
 view_item_code varchar(25),
 year_code varchar(4),
 view_year_type varchar(1),
 season_code varchar(1),
 scm_country_code varchar(3),
 color_code varchar(10),
 size_code varchar(10),
 pattern_length_code varchar(10),
 major_category_code numeric(4) NOT NULL,
 class_code numeric(4) NOT NULL,
 middle_category_code numeric(4) NOT NULL,
 item_parent varchar(25),
 item_crand_parent varchar(25),
 item_level numeric(1) NOT NULL,
 transaction_level numeric(1) NOT NULL,
 pack_type varchar(1) NOT NULL,
 simple_pack_kind varchar(1) NOT NULL,
 contains_inner_kind varchar(1) NOT NULL,
 sellable_type varchar(1) NOT NULL,
 orderable_type varchar(1) NOT NULL,
 pack_status varchar(1),
 receive_unit varchar(1),
 asort_code varchar(4),
 cost_price_sequence numeric(3),
 initial_selling_price numeric(20,4),
 retail_zone_group_id numeric(4),
 intern_item_name varchar(250) NOT NULL,
 pos_item_name varchar(120) NOT NULL,
 second_pos_item_name varchar(120),
 external_item_name_1 varchar(66),
 external_item_name_2 varchar(66),
 external_item_name_3 varchar(66),
 external_item_name_4 varchar(66),
 second_item_name varchar(255) NOT NULL,
 picking_shipment_type varchar(1) NOT NULL,
 regular_item_type varchar(1) NOT NULL,
 color_size_management_type varchar(1) NOT NULL,
 b_item_return_possible_type varchar(1) NOT NULL,
 status varchar(1) NOT NULL,
 delivery_type_code varchar(6) NOT NULL,
 supplier_code numeric(10) NOT NULL,
 stock_buying_cost numeric(20,4),
 system_country_code varchar(3) NOT NULL,
 uda_value numeric(5),
  CONSTRAINT w_item_pk
   PRIMARY KEY(lot_number,system_business_code,system_country_code,supplier_code,item_code,eai_update_date)
)
WITH (OIDS=FALSE,FILLFACTOR=90)
;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA scm TO scmuser; 
GRANT SELECT ON ALL TABLES IN SCHEMA scm TO scmview; 

commit;
