CREATE
OR REPLACE VIEW scm.v_item(
 lot_number,
 eai_update_date,
 eai_update_type,
 eai_send_status,
 eai_send_date,
 system_brand_code,
 system_business_code,
 system_country_code,
 item_code,
 item_code_type,
 view_item_code,
 year_code,
 view_year_type,
 season_code,
 detail_season_code,
 scm_country_code,
 color_code,
 size_code,
 pattern_length_code,
 major_category_code,
 class_code,
 middle_category_code,
 small_category_value,
 item_parent,
 item_crand_parent,
 item_level,
 transaction_level,
 pack_flag,
 simple_item_pack_flag,
 contains_inner_kind,
 sellable_flag,
 orderable_flag,
 pack_status,
 order_unit_type,
 asort_code,
 fob,
 cost_price_sequence,
 stock_buying_type_code,
 initial_selling_price,
 scm_zone_group,
 standard_scm_unit,
 item_name,
 intern_item_name,
 pos_item_name,
 second_pos_item_name,
 external_item_name_1,
 external_item_name_2,
 external_item_name_3,
 external_item_name_4,
 second_item_name,
 picking_shipment_flag,
 direct_delivery_unit_quantity,
 regular_item_flag,
 color_size_management_flag,
 b_item_return_possible_flag,
 status,
 delivery_type_code,
 supplier_code,
 stock_buying_cost,
 packing_quantity,
 picking_unit_quantity,
 selling_price,
 selling_unit,
 taxation_flag,
 batch_region
) AS (
 SELECT
  w_item.lot_number,
  w_item.eai_update_date,
  w_item.eai_update_type,
  w_item.eai_send_status,
  w_item.eai_send_date,
  m_trans_business_code.system_brand_code,
  m_trans_business_code.system_business_code,
  m_trans_business_code.system_country_code,
  w_item.item_code,
  CAST(null AS varchar(6)) item_code_type,
  w_item.view_item_code,
  w_item.year_code,
  w_item.view_year_type,
  w_item.season_code,
  CAST(null AS varchar(6)) detail_season_code,
  w_item.scm_country_code,
  w_item.color_code,
  w_item.size_code,
  w_item.pattern_length_code,
  w_item.major_category_code,
  w_item.class_code,
  w_item.middle_category_code,
  w_item.uda_value,
  w_item.item_parent,
  w_item.item_crand_parent,
  w_item.item_level,
  w_item.transaction_level,
  CAST(w_item.pack_type as boolean) pack_flag,
  CAST(w_item.simple_pack_kind as boolean) simple_item_pack_flag,
  w_item.contains_inner_kind,
  CAST(w_item.sellable_type as boolean) sellable_flag,
  CAST(w_item.orderable_type as boolean) orderable_flag,
  w_item.pack_status,
  w_item.receive_unit,
  w_item.asort_code,
  CAST('0' AS numeric(10,4)) fob,
  w_item.cost_price_sequence,
  CAST(null AS varchar(6)) stock_buying_type_code,
  w_item.initial_selling_price,
  w_item.retail_zone_group_id,
  CAST(null AS varchar(4)) standard_scm_unit,
  CAST(null AS varchar(250)) item_name,
  w_item.intern_item_name,
  w_item.pos_item_name,
  w_item.second_pos_item_name,
  w_item.external_item_name_1,
  w_item.external_item_name_2,
  w_item.external_item_name_3,
  w_item.external_item_name_4,
  w_item.second_item_name,
  CAST(w_item.picking_shipment_type AS boolean) picking_shipment_flag,
  CAST('0' AS numeric(8)) direct_delivery_unit_quantity,
  CAST(w_item.regular_item_type AS boolean) regular_item_flag,
  CAST(w_item.color_size_management_type AS boolean) color_size_management_flag,
  CAST(w_item.b_item_return_possible_type AS boolean) b_item_return_possible_flag,
  w_item.status,
  w_item.delivery_type_code,
  w_item.supplier_code,
  w_item.stock_buying_cost,
  CAST('0' AS numeric(8)) packing_quantity,
  CAST('0' AS numeric(8)) picking_unit_quantity,
  CAST('0' AS numeric(20,4)) selling_price,
  CAST(null AS varchar(4)) selling_unit,
  CAST(false AS boolean) taxation_flag,
  w_item.batch_region
 FROM
  scm.w_item,
  scm.m_trans_business_code
 WHERE
  w_item.item_level = 3
  AND w_item.batch_region = m_trans_business_code.batch_region
  AND w_item.system_business_code = m_trans_business_code.system_business_code
  AND w_item.system_country_code = m_trans_business_code.system_country_code
)
;

GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON ALL TABLES IN SCHEMA scm TO scmuser;
GRANT SELECT ON ALL TABLES IN SCHEMA scm TO scmview;
