INSERT INTO scm.m_pay_off_summary_mapping VALUES
 (2,'CANADA_STORE','C001',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','C002',8,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','C005',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','C007',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T001',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T002',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T003',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T004',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T007',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T011',12,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T012',12,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T014',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T015',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T016',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T017',6,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T018',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','T019',null,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','E001',3,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 (2,'CANADA_STORE','EX001',2,'0001','17','17','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration');

