INSERT INTO scm.m_common_code_master VALUES
 ('consistency_scm_flag','false','1','Corporate No scm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('consistency_scm_flag','true','2','Corporate scm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','CAD','1','Canadian dollar','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','EUR','2','Euro','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','USD','3','US Dollar','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','JPY','4','Japanese Yen','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','GBP','5','UK Pound','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','TWD','6','New Taiwan dollar','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','BGN','7','Bulgarian Lev','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','HRK','8','Kuna','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','CZK','9','Koruna','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','DKK','10','Danish krone ','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','HUF','11','Forint ','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','SEK','12','Krone','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','LVL','13','Lats','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','LTL','14','Litas','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','PLN','15','Zloty','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('currency_code','ROL','16','Leu','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('EMPLOYEE_DISCOUNT_FLAG','false','1','Not apply staff discount ','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('EMPLOYEE_DISCOUNT_FLAG','true','2','Apply staff discount ','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','01','1','Abnormal value in required field','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','02','2','scm transaction without Item','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','03','3','Business error','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','04','4','Abnormal business date','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','05','5','scm transaction before store opening','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','06','6','scm transaction after store closing','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','07','7','Exceed business date closing time','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','08','8','Closed business date','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','09','9','Invalid tender','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','10','10','Balance inconsistency','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','11','11','Unique constraint error','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','12','12','scm payoff inconsistency','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('error_type','13','13','no error','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C001','1','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DACNTR','1','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C002','2','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCASH','2','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C003','3','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCCARD','3','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C004','4','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCHECK','4','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C005','5','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCOD','5','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C006','6','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCOUP2','6','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C007','7','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCOUP3','7','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C009','8','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCOUP4','8','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C101','9','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DCOUPN','9','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C102','10','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DDEFER','10','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C103','11','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DEMDSC','11','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C104','12','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DGCARD','12','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C105','13','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DGHGCA','13','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C109','14','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DGHGCE','14','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C202','15','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DGHGCS','15','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C204','16','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DGMKCS','16','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','C209','17','ITEMscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DGPDSC','17','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DMCARD','18','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DNTDSC','19','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DPCAR2','20','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DPCARD','21','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DPOTSF','22','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DROUAM','23','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DSPGCS','24','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DTOKEN','25','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DTOKNT','26','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DTRVCH','27','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DTXDIF','28','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DTXDS2','29','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DTXDSC','30','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DUHGCA','31','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DUHGCE','32','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DUHGCS','33','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DUMKCS','34','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','DADRCV','35','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','CASHDR','36','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','RSVCHG','37','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','E001','38','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','E002','39','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T001','40','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T002','41','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T003','42','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T004','43','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T006','44','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T007','45','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T008','46','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T009','47','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T011','48','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T012','49','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T013','50','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T014','51','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T015','52','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T016','53','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T017','54','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T018','55','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T019','56','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T020','57','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T023','58','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T024','59','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T025','60','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T027','61','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T028','62','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T102','63','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T106','64','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T107','65','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T108','66','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T125','67','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T201','68','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T206','69','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T208','70','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('MAPPING_SUB_PATTERN_L3','T225','71','PAYMENTTENDER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','ORDER_ACCEPTANCE','1','Order Acceptance','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','SHIPMENT_PENDING','2','Shipment Pend','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','SHIPMENT_ORDER_WAIT','3','Shipment Order Wait','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','SHIPMENT_ORDERED','4','Shipment Ordered','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','SHIPMENT_CONFIRMED','5','Shipment confirmed','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','DELIVERY_COMPLETE','6','Delivery Complete','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','RETURNING_ITEM_CONFIRMED','7','Order Canceled','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ORDERSTATUS','STORE_PAYMENT','8','Store Payment','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('payment_sign','P','1','Positive','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('payment_sign','N','2','Negative','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DACNTR','1','Accounts receivable','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCASH','2','Cash','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCCARD','3','Credit','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCHECK','4','Check','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCOD','5','Uncollected deposit (Cash-on-delivery)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCOUP2','6','Coupon (Tax free)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCOUP3','7','Coupon (Manual input)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCOUP4','8','Coupon (Manual input) (Tax free)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DCOUPN','9','Coupon','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DDEFER','10','Deferred payment (Convenience store/Bank/Post office)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DEMDSC','11','Employee discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DGCARD','12','Gift card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DGHGCA','13','GU gift card deposit','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DGHGCE','14','GU gift card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DGHGCS','15','GU gift card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DGMKCS','16','GU Promotion','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DGPDSC','17','FR Group Employee Discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DMCARD','18','Merchandise Credit','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DNTDSC','19','NET discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DPCAR2','20','Point card (Tax free)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DPCARD','21','Point card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DPOTSF','22','Postal money order','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DROUAM','23','Rounding Amount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DSPGCS','24','Promotion gift card activate','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DTOKEN','25','Token','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DTOKNT','26','Gift Card Redeem (Non-Tax)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DTRVCH','27','Travellers check','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DTXDIF','28','Consumption tax discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DTXDS2','29','Tax free service amount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DTXDSC','30','Service amount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DUHGCA','31','UQ gift card deposit','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DUHGCE','32','UQ gift card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DUHGCS','33','UQ gift card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DUMKCS','34','UQ Promotion','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','DADRCV','35','Advances','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','CASHDR','36','Cash in drawer','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','RSVCHG','37','reserve for change','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','E001','38','Number of customers','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','E002','39','Cash overs and shorts','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T001','40','Item scm (Cancel after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T002','41','Item scm (Return after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T003','42','Discount after subtotal (Tax excluded)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T004','43','Reprint receipt quantity','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T006','44','Non-item scm (Return after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T007','45','Item return','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T008','46','Non-item return','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T009','47','Point card','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T011','48','Cash employee sale','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T012','49','Credit card employee sale','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T013','50','Number of cancellation','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T014','51','New price','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T015','52','Bundle scm discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T016','53','Single item percentage discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T017','54','Percentage discount after subtotal','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T018','55','Single item discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T019','56','Discount after subtotal','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T020','57','Group company scm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T023','58','scm return','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T024','59','Temporary received consumption tax excluded (Old tax rate)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T025','60','Number of customers','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T027','61','ENURIscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T028','62','PointDiscountscm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T102','63','Tax free item scm (Return after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T106','64','Tax free non-item scm (Return after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T107','65','Tax free item return','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T108','66','Tax free non-item return','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T125','67','Number of customers (Tax free)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T201','68','Item scm which are not target (Cancel after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T206','69','Non-item scm which are not target (Return after closing store)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T208','70','Non-item return which are not target','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','T225','71','Number of customers (Not target) ','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C001','72','Item scm (scm)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C002','73','Item scm (Cancel)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C003','74','Item scm (Return)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C004','75','Non-item scm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C005','76','Miscellaneous income','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C006','77','Temporary received consumption tax included','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C007','78','Temporary received consumption tax excluded','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C009','79','Non-item scm (Return)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C101','80','Tax free item scm (scm)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C102','81','Tax free item scm (Cancel)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C103','82','Tax free item scm (Return)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C104','83','Tax free non-item scm','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C105','84','Tax free miscellaneous income','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C109','85','Tax free non-item scm (Return)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C202','86','Item scm which are not target (Cancel)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C204','87','Non-item scm which are not target','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PAY_OFF_CODE','C209','88','Non-item scm which are not target (Return)','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PRODUCT_CLASSIFICATION','ITEM','1','Item','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PRODUCT_CLASSIFICATION','NMITEM','2','Non-Item','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('promotion_type','1000','1','Mix&Match','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('promotion_type','1002','2','Multi Unit','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('promotion_type','1003','3','Single Promotion','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('promotion_type','1004','4','Store Discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('promotion_type','1007','5','Limited','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('quantity_code','P','1','Positive','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('quantity_code','N','2','Negative','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('RTLOG','SLSTX','1','scm Tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('RTLOG','VAT','2','Tax Inclusive Price','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('RTLOG','CNSMP','3','Tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('scm_linkage_type','0','1','scm linkage','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('scm_linkage_type','1','2','Not scm linkage','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('scm_transaction_discount_flag','false','1','Not apply subtotal discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('scm_transaction_discount_flag','true','2','Apply subtotal discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('Sign_Column_printing_on_scm_Report','NotPrint','1','NotPrint','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('Sign_Column_printing_on_scm_Report','Print','2','Print','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('STORE_DISCOUNT_TYPE','01','1','Discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('STORE_DISCOUNT_TYPE','02','2','Bundle Sale discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('STORE_DISCOUNT_TYPE','03','3','Subtotal discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('STORE_DISCOUNT_TYPE','04','4','New price','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_brand_code','0001','1','UQ','UNIQLO','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_brand_code','0005','2','GU','GU','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_brand_code_screen','UQ','1','UNIQLO','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_brand_code_screen','GU','2','GU','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','1','1','UQJP','UQJP','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','2','2','UQUK','UQUK','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','3','3','FRCN','FRCN','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','4','4','UQUS','UQUS','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','5','5','FRLK','FRLK','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','6','6','UQHK','UQHK','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','7','7','UQF','UQF','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','8','8','UQSG','UQSG','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','9','9','UQRUS','UQRUS','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','10','10','UQTW','UQTW','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','11','11','UQTH','UQTH','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','12','12','FRPH','FRPH','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','13','13','FRID','FRID','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','14','14','UQAU','UQAU','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','17','15','UQCD','UQCD','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','60','16','GUJP','GUJP','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','61','17','GUCN','GUCN','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','62','18','GUTW','GUTW','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_business_code','63','19','GUHK','GUHK','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','1','1','JP','Japan','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','2','2','UK','United Kingdom','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','3','3','CN','China','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','4','4','US','United States','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','5','5','KR','Korea','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','6','6','HK','Hong Kong','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','7','7','FR','France','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','8','8','SG','Singapore','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','9','9','RU','Russia','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','10','10','TW','Taiwan','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','11','11','TH','Thailand','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','12','12','PH','Philippines','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','13','13','ID','Indonesia','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','14','14','AU','Australia','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','15','15','DE','Germany','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','16','16','ES','Spain','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','17','17','CA','Canada','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','26','18','MO','Macau','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','27','19','MY','Malaysia','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code','32','20','BE','Belgium','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','JP','1','Japan','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','UK','2','United Kingdom','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','CN','3','China','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','US','4','United States','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','KR','5','Korea','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','HK','6','Hong Kong','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','FR','7','France','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','SG','8','Singapore','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','RU','9','Russia','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','TW','10','Taiwan','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','TH','11','Thailand','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','PH','12','Philippines','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','ID','13','Indonesia','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','AU','14','Australia','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','DE','15','Germany','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','ES','16','Spain','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','CA','17','Canada','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','MO','18','Macau','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','MY','19','Malaysia','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('system_country_code_screen','BE','20','Belgium','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('tax_group','GST','1','Goods and Services Tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('tax_group','PST','2','Provincial scm Tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('tax_group','HST','3','Harmonized scm Tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('tax_group','RST','4','provincial Retail scm Taxes','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('tax_group','QST','5','Quebec scm tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('TAX_KIND','IN','2','Tax-inclusive','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('TAX_KIND','OUT','1','Tax-exclusive','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('TAXATION_TYPE','N','2','Tax free','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('TAXATION_TYPE','Y','1','Tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('total_type','ITEM','1','ITEM','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('total_type','SHIPPING','2','SHIPPING','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('total_type','COUPON','3','COUPON','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('total_type','OTHER','4','OTHER','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('transaction_type','SALE','1','SALE','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('transaction_type','RETURN','2','RETURN','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('transaction_type','PVOID','3','PVOID','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101001','0','1','Enter Detail field(Convert Business)','0','SSLS1500101003','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101001','1','2','Enter Detail field(General Data Deletion)','1','SSLS1500101004','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101001','2','2','Enter Detail field(Store Control)','0','SSLS1500101005','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101001','3','1','Enter Detail field(Tender Conversion)','1','SSLS1500101006','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101001','4','3','Enter Detail field(Store General Purpose Information)','0','SSLS1500101007','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101003','0','0','m_trans_business_code','m_trans_business_code','Enter Detail field(Convert Business)','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101004','0','0','m_general_delete_setting','m_general_delete_setting','Enter Detail field(General Data Deletion)','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101005','0','0','m_store_control','m_store_control','Enter Detail field(Store Control)','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101006','0','0','m_trans_tender','m_trans_tender','Enter Detail field(Tender Conversion)','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('SSLS1500101007','0','0','m_store_general_purpose','m_store_general_purpose','Enter Detail field(Store General Purpose Information)','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PR_LIST_MAX','SSLS1500101002','0','10','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PR_LIST_MAX','SSLS1500101003','0','10','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PR_LIST_MAX','SSLS1500101005','0','10','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PR_LIST_MAX','SSLS1500101006','0','10','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('PR_LIST_MAX','SSLS1500101007','0','10','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('batch_region','21','1','ASIA','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('batch_region','22','2','EU','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('batch_region','23','3','US','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('batch_region','24','4','JP','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('batch_region','25','5','GU','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_dclose_send','1','w_dclose_send','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_type','2','w_type','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','t_ims_scm_transaction_header','3','t_ims_scm_transaction_header','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','t_ims_scm_transaction_detail','4','t_ims_scm_transaction_detail','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','t_ims_scm_transaction_discount','5','t_ims_scm_transaction_discount','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','t_ims_scm_transaction_tax','6','t_ims_scm_transaction_tax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','t_ims_scm_transaction_tender','7','t_ims_scm_transaction_tender','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','t_ims_pay_off_data','8','t_ims_pay_off_data','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_item','9','w_item','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_store','10','w_store','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_non_item','11','w_non_item','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_g_class','12','w_g_class','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_purge_item','13','w_purge_item','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('delete_target_table','w_trans_store_code','14','w_trans_store_code','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('date_item','create_datetime','1','Create DateTime','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('date_item','update_datetime','2','Update DateTime','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Santa_Isabel','1','America/Santa_Isabel','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Los_Angeles','2','America/Los_Angeles','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Chihuahua','3','America/Chihuahua','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Phoenix','4','America/Phoenix','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Denver','5','America/Denver','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Guatemala','6','America/Guatemala','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Chicago','7','America/Chicago','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Regina','8','America/Regina','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Mexico_City','9','America/Mexico_City','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Bogota','10','America/Bogota','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Indiana/Indianapolis','11','America/Indiana/Indianapolis','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/New_York','12','America/New_York','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Caracas','13','America/Caracas','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Halifax','14','America/Halifax','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Asuncion','15','America/Asuncion','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/La_Paz','16','America/La_Paz','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Cuiaba','17','America/Cuiaba','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Santiago','18','America/Santiago','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/St_Johns','19','America/St_Johns','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Sao_Paulo','20','America/Sao_Paulo','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Godthab','21','America/Godthab','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Cayenne','22','America/Cayenne','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Argentina/Buenos_Aires','23','America/Argentina/Buenos_Aires','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('time_zone','America/Montevideo','24','America/Montevideo','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ec_flag','0','1','Non EC','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('ec_flag','1','2','EC','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('integrity_check_type','0','1','Not Check','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('integrity_check_type','1','2','Matched','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('integrity_check_type','2','3','Payoff Value Mismatch','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('integrity_check_type','3','4','Balance Mismatch','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('data_alteration_status','0','1','Not corrected','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('data_alteration_status','1','2','Corrected','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('data_alteration_status','2','3','Correcting','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('amount_sign','P','1','Positive','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration'),
 ('amount_sign','N','2','Negative','','','','','Migration',current_timestamp,'Migration','Migration',current_timestamp,'Migration');

